### ISSUE TITLE
QuarkusTopicDiscoveryTest failure in quarkus3 migration branch

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie-kogito-runtimes#3288]
### Describe the bug

Currently I'm working on quarkus3 migration branch and QuarkusTopicDiscoveryTest fails probably because of `@SetSystemProperty`

```
[INFO] Running org.kie.kogito.addon.quarkus.messaging.common.QuarkusTopicDiscoveryTest
[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.103 s <<< FAILURE! -- in org.kie.kogito.addon.quarkus.messaging.common.QuarkusTopicDiscoveryTest
[ERROR] org.kie.kogito.addon.quarkus.messaging.common.QuarkusTopicDiscoveryTest.verifyTopicsWithPropertiesSameTopic -- Time elapsed: 0.018 s <<< FAILURE!
java.lang.AssertionError: 

Expected size: 2 but was: 0 in:
[]
	at org.kie.kogito.addon.quarkus.messaging.common.QuarkusTopicDiscoveryTest.verifyTopicsWithPropertiesSameTopic(QuarkusTopicDiscoveryTest.java:68)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[ERROR] org.kie.kogito.addon.quarkus.messaging.common.QuarkusTopicDiscoveryTest.verifyTopicsWithPropertiesSet -- Time elapsed: 0.004 s <<< FAILURE!
java.lang.AssertionError: 

Expected size: 2 but was: 0 in:
[]
	at org.kie.kogito.addon.quarkus.messaging.common.QuarkusTopicDiscoveryTest.verifyTopicsWithPropertiesSet(QuarkusTopicDiscoveryTest.java:51)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   QuarkusTopicDiscoveryTest.verifyTopicsWithPropertiesSameTopic:68 
Expected size: 2 but was: 0 in:
[]
[ERROR]   QuarkusTopicDiscoveryTest.verifyTopicsWithPropertiesSet:51 
Expected size: 2 but was: 0 in:
[]
[INFO] 
[ERROR] Tests run: 14, Failures: 2, Errors: 0, Skipped: 0
```

Note that if you run the whole test class, the 2 test methods fail, but if you run the specific test method, it succeeds.

https://kie.zulipchat.com/#narrow/stream/381961-drools-dev/topic/Quarkus.203.20migration/near/403630691

### Expected behavior

All tests in QuarkusTopicDiscoveryTest pass.

### Actual behavior

2 test methods in QuarkusTopicDiscoveryTest fail.

### How to Reproduce?

Build drools quakus3 branch
- git clone https://github.com/apache/incubator-kie-drools.git
- cd incubator-kie-drools
- git checkout -b quakus3 origin/quarkus3
- mvn clean install -Dquickly

Build kogito-runtimes quakus3 branch **(not yet ready: To be updated)**
- git clone https://github.com/apache/incubator-kie-kogito-runtimes.git
- cd incubator-kie-kogito-runtimes
- git checkout -b quakus3 origin/quarkus3
- mvn clean install -Dquickly
- cd quarkus/addons/messaging
- mvn verify

### Output of `uname -a` or `ver`

Linux tkobayas.nrt.csb 4.18.0-477.27.1.el8_8.x86_64 #1 SMP Thu Aug 31 10:29:22 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

3.0.0-SNAPSHOT (as updated by quakus3 migration)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)

### Additional information

Currently the quarkus3 migration code exists in https://github.com/tkobayas/kogito-runtimes/tree/test-quarkus3

I'll raise a PR soon.

**Comment by ricardozanini** [comment]
Thank you for the detailed description, @tkobayas 🙏

**Comment by tkobayas** [comment]
Updated the reproduce steps to meet mario's branches.
