### ISSUE TITLE
Serverless workflow with custom events does not work in Kogito 10.0.0

### ISSUE THREAD

**Issue by shootsoft** [apache/incubator-kie-kogito-runtimes#3820]
### Describe the bug

In Kogito's 1.44.0.Final, I have some custom events defined in workflow

```yaml
events:
- name: myCallbackEvent
  source: ""
  type: myCallbackEvent
...
states:
- name: OnCallbackEvent
  type: event
  onEvents:
  - eventRefs:
    - myCallbackEvent
    actions:
    - functionRef:
        ...
  transition: checkMyCallbackEvent
```

These events are not start form the "start" point, but triggered through java code

```java
var app = new StaticWorkflowApplication();
var process = app.process(workflow);
var model = new JsonNodeModel(...);
var instance = process.createInstance(model);
instance.start();
instance.send(Sig.of(channel, eventData));
```

Now, when I tried to upgarde to Kogito 10.0.0, my application started to fail at this line

```
var process = app.process(workflow);
```

With error 

```
java.lang.IllegalStateException: Process could not be validated ![Process 'MyWorkflow' [MyWorkflow]: Node 'OnCallbackEvent' [58] Embedded subprocess does not have incoming connection....

	at org.jbpm.ruleflow.core.RuleFlowProcessFactory.validate(RuleFlowProcessFactory.java:244)
	at org.kie.kogito.serverless.workflow.parser.ServerlessWorkflowParser.parseProcess(ServerlessWorkflowParser.java:173)
	at org.kie.kogito.serverless.workflow.parser.ServerlessWorkflowParser.getProcessInfo(ServerlessWorkflowParser.java:184)
	at org.kie.kogito.serverless.workflow.executor.StaticWorkflowApplication.createProcess(StaticWorkflowApplication.java:330)
	at org.kie.kogito.serverless.workflow.executor.StaticWorkflowApplication.process(StaticWorkflowApplication.java:283)

```

How can I skip this validation with embedded mode in Kogito 10.0.0?

### Expected behavior

No failures with Kogito 10.0.0 because they work well in 1.44.0

### Output of `java -version`

17

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

10.0.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by fjtirado** [comment]
@shootsoft  There are two issues here. 

1. The workflow definition that use to work is not working anymore, we need a reproducer for that (or the complete workflow definition). That validation is required, so there is either a bug in the code or in the definition, thats why we need the complete definition. 
2. This is minor, but I think you should take a look at an example of embedded workflow usage with events (so you avoid using the internal API to signal the event) https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/kogito-serverless-workflow/kogito-serverless-workflow-executor-tests/src/test/java/org/kie/kogito/serverless/workflow/executor/PersistentApplicationTest.java#L74-L94
